### ISSUE TITLE
how to update it to last version?

### ISSUE THREAD

**Issue by tvvocold** [praswicaksono/openshift-opencart#1]
thx

**Comment by praswicaksono** [comment]
will update to last version, just stay tune

**Comment by tvvocold** [comment]
ok, nice! but how and when

**Comment by praswicaksono** [comment]
You have installed it and want to upgrade? Or you want make new install with latest version?

**Comment by tvvocold** [comment]
i had installed it and wanna to update it.
or i cloud make a new install if needed.

**Comment by praswicaksono** [comment]
Okay will update it in couple of minutes

**Comment by tvvocold** [comment]
thx
